[package]
name = "rust_ntt"
version = "0.1.1"
edition = "2024"

[dependencies]
rand = "0.9.1"

[dev-dependencies] 
criterion = "0.6.0"

[lib]
name = "rust_ntt"
path = "src/lib.rs"

[[bench]]
name = "benches"
harness = false
